#! /bin/bash

startup()
{
  echo '################'
  echo '# Sovi Server! #'
  echo '################'

  # Hack for Django Settings
  export DJANGO_SETTINGS_MODULE="sovi.settings"

  postgres -D /usr/local/var/postgres &
  POSTGRE_PID=$!

  gunicorn sovi.wsgi -b 192.168.1.8:8000 &
  GUNICORN_PID=$!

  compass watch ./sovi &
  COMPASS_PID=$!

}

close() 
{
  kill $POSTGRE_PID
  wait $POSTGRE_PID
  
  kill $GUNICORN_PID
  wait $GUNICORN_PID

  kill $COMPASS_PID
  wait $COMPASS_PID

  echo ''
  echo '#############'
  echo '# Good Bye! #'
  echo '#############'
  exit 0
}

# trap keyboard interrupt (control-c) & start
trap close SIGINT

# Start everything then go wait
startup

while true; do sleep 1; done
